name: SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para análise completa

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"NunoMiranda19_TheShopCartGHATest" \
            /o:"nunomiranda19" \
            /d:sonar.login=${{ secrets.SONAR_TOKEN }} \
            /d:sonar.exclusions=**/*.yml,**/*.yaml,**/*.json \
            /d:sonar.cs.opencover.reportsPaths=TestResults/coverage.opencover.xml

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test TheShopCartGHATest.sln --configuration Release --no-build \
             /p:CollectCoverage=true \
             /p:CoverletOutput=TestResults/coverage.opencover.xml \
             /p:CoverletOutputFormat=opencover

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
