name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para análise completa

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore

      - name: Begin Sonar analysis
        run: |
          dotnet sonarscanner begin \
            /k:"nunomiranda19" \
            /o:"NunoMiranda19" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.exclusions=**/*.yml,**/*.yaml,**/*.json \
            /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test TheShopCartGHATest.sln --configuration Release --no-build \
             /p:CollectCoverage=true \
             /p:CoverletOutput=TestResults/ \
             /p:CoverletOutputFormat=opencover

      - name: End Sonar analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
