name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para sonar

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore YourSolution.sln

      - name: Build solution
        run: dotnet build YourSolution.sln --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test YourSolution.sln --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"NunoMiranda19_TheShopCartGHATest" /d:sonar.host.url="https://sonarcloud.io" /o:"SEU_ORG" /d:sonar.login="$env:SONAR_TOKEN" /d:sonar.cs.opencover.reportsPaths="**/TestResults/coverage.opencover.xml"
          dotnet build ShopCartSolution.sln --no-incremental
          dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"
